export const site = {
  title: '燎原之火',
  subtitle: 'ZM-BAD的小站',
  keywords: '计算机技术, Linux, Python, Web, Java',
  description: '欢迎来访我的世界',
  url: 'https://zmbad.me',
  pageNoTitle: '燎原之火 | ZM-BAD的小站',
  author: 'ZM-BAD',
  email: 'prozm.bad@gmail.com',
  perPage: 8,
  menu: [
    { page: '首页', directory: '', icon: 'icon-home' },
    { page: '归档', directory: 'archives/', icon: 'icon-archive' },
    { page: '标签', directory: 'tags/', icon: 'icon-tags' },
    { page: '分类', directory: 'category/', icon: 'icon-post-category' },
    { page: '关于', directory: 'about/', icon: 'icon-about' },
  ],
  links: [{ title: 'Astro', url: 'https://astro.build/' }],
  codehub: [{ title: 'GitHub', url: 'https://github.com/ZM-BAD' }],
};
